ctrl_interface=/var/run/hostapd
ctrl_interface_group=netdev
country_code=YE
ieee80211d=1

interface=wlan2
driver=nl80211
ssid=OSU_Welcome_Shop
hw_mode=g
channel=1
ieee80211n=1
ieee80211w=2
wmm_enabled=1

# --- HS2.0 + Interworking إعلان OSU ---
interworking=1
hs20=1
hs20_release=2
access_network_type=15
internet=0
anqp_domain_id=1234
domain_name=ourmemora.com
venue_group=7
venue_type=1
venue_name=eng:Welcome Shop
hs20_oper_friendly_name=eng:Welcome Shop Wi-Fi
hs20_conn_capab=6:80:1
hs20_conn_capab=17:123:1
nai_realm=0,ourmemora.com,"EAP:TTLS,MSCHAPV2;EAP:PEAP,MSCHAPV2"
gas_address3=1

# --- OSU Info ---
osu_server_uri=https://sensora.ourmemora.com/osu/
osu_friendly_name=eng:Welcome Shop Wi-Fi
osu_service_desc=eng:Sign up for free Wi-Fi
osu_method_list=1
osu_nai=anonymous@ourmemora.com
osu_ssid="OSU_Welcome_Shop"

# OSEN (Secure OSU BSS)
wpa=2
osen=1
wpa_key_mgmt=OSEN
rsn_pairwise=CCMP
hs20_conn_capab=6:443:1
hs20_conn_capab=17:53:1
bridge=br-osu
ctrl_interface=/var/run/hostapd
ctrl_interface_group=netdev
