ctrl_interface=/var/run/hostapd
ctrl_interface_group=netdev

country_code=YE
ieee80211d=1

interface=wlan0
driver=nl80211
ssid=Welcome_Shop_FreeWiFi
hw_mode=g
channel=6
ieee80211n=1
ieee80211w=1
wmm_enabled=1

# Hotspot 2.0 / 802.11u 
interworking=1
access_network_type=3
internet=1
hs20=1
hs20_release=2
anqp_domain_id=1234
domain_name=ourmemora.com

venue_group=7
venue_type=1
venue_name=eng:Welcome Shop
hs20_oper_friendly_name=eng:Welcome Shop Wi-Fi

hs20_conn_capab=6:80:1
hs20_conn_capab=6:443:1
hs20_conn_capab=17:53:1

# realms للبروفايل بعد الاشتراك
nai_realm=0,ourmemora.com,"EAP:TTLS,MSCHAPV2;EAP:PEAP,MSCHAPV2"

gas_address3=0

# إعلان مزود OSU على الـ BSS الرئيسي
osu_ssid="OSU_Welcome_Shop"
osu_server_uri=https://sensora.ourmemora.com/osu/
osu_friendly_name=eng:Welcome Shop Wi-Fi
osu_service_desc=eng:Sign up for free Wi-Fi
osu_nai=anonymous@ourmemora.com
osu_method_list=1

# WPA-Enterprise
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee8021x=1
eap_server=0
own_ip_addr=192.168.50.1
auth_server_addr=127.0.0.1
auth_server_port=1812
auth_server_shared_secret=secret123
acct_server_addr=127.0.0.1
acct_server_port=1813
acct_server_shared_secret=secret123
