interface=wlan0
dhcp-range=192.168.4.10,192.168.4.200,255.255.255.0,12h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
address=/#/192.168.4.1

# ========== Captive Portal ==========
# Apple
address=/captive.apple.com/192.168.4.1
address=/applednld.apple.com/192.168.4.1
address=/apple.com/192.168.4.1
# Android
address=/www.apple.com/192.168.4.1
address=/connectivitycheck.android.com/192.168.4.1
address=/android.clients.google.com/192.168.4.1
# Microsoft
address=/clients3.google.com/192.168.4.1
address=/msftconnecttest.com/192.168.4.1
address=/www.msftconnecttest.com/192.168.4.1
address=/nmcheck.gnome.org/192.168.4.1
address=/detectportal.firefox.com/192.168.4.1

server=8.8.8.8
server=8.8.4.4
log-dhcp
log-queries
log-facility=/var/log/dnsmasq.log
