interface=wlan0
driver=nl80211
ssid=Shop_Welcome_OSU
hw_mode=g
channel=6
#country_code=EG
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=SecurePass123!@#
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP  
wmm_enabled=1

# ========== Hotspot 2.0 ==========
hs20=1
interworking=1
access_network_type=2
internet=1
asra=0
esr=0
uesa=0
venue_group=2
venue_type=8
roaming_consortium=5A5A5A
domain_name=iot.com 
nai_realm=0, "iot.com", 21, 13
osu_ssid=Shop_Welcome_OSU
osu_method_list=1
osu_friendly_name=eng:"Welcome to Our Shop"
osu_server_uri=http://192.168.4.1/  
osu_nai=not_available
osen=1
macaddr_acl=0