interface=br-osu
bind-interfaces
except-interface=lo
no-dhcp-interface=wlan0
no-dhcp-interface=wlan1
no-dhcp-interface=eth0

dhcp-range=br-osu,192.168.60.10,192.168.60.200,255.255.255.0,12h
dhcp-option=br-osu,3,192.168.60.1
dhcp-option=br-osu,6,1.1.1.1,8.8.8.8
dhcp-authoritative

